### ISSUE TITLE
Add handling for case when alchemyAPI does not return JSON in response

### ISSUE THREAD

**Issue by mandeepm91** [ericberlow/openmappr#11]
The code here expects the response to be JSON. We need to add a `try/catch` block to make sure we handle the scenario when the response is not a JSON. 

https://github.com/ericberlow/openmappr/blob/7ccca533d7be505cd125d335512ae41953861086/server/libs/alchemyapi.js#L190

This caused error on server

```
web_1            | POST /api/orgs/5b8389d72392d300110d5a61/projects/5b8aa6c660925e0017a19bea/di/alchemyapi 200 131.726 ms - 126
web_1            | 2018-09-01 14:51:39 LOG connected to the socket for taskId 5b8aa77b60925e0017a19c0d
web_1            | undefined:1
web_1            | <PRE>
web_1            | ^
web_1            | 
web_1            | SyntaxError: Unexpected token < in JSON at position 0
web_1            |     at JSON.parse (<anonymous>)
web_1            |     at IncomingMessage.<anonymous> (/usr/src/mappr/server/libs/alchemyapi.js:190:49)
web_1            |     at emitNone (events.js:111:20)
web_1            |     at IncomingMessage.emit (events.js:208:7)
web_1            |     at endReadableNT (_stream_readable.js:1064:12)
web_1            |     at _combinedTickCallback (internal/process/next_tick.js:138:11)
web_1            |     at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

**Comment by ericberlow** [comment]
hi mandeep - i tried what michael did - uploaded the attached file and linked by 'abstract' - which is a bit block of text for each node.   Athena appears to have crashed when I did it.  [PeaceRefs_2017-07-08_nodes.xlsx](https://github.com/ericberlow/openmappr/files/2345967/PeaceRefs_2017-07-08_nodes.xlsx)

**Comment by mandeepm91** [comment]
I tried uploading the excel and linking by astract. This one gives a different error. No issues in athena. There is an error coming in the web app itself. Here is the error:

```
web_1            | 2018-09-03 15:31:03 LOG Found Mapping 5b8d53b7f763250001cb5eb4 -> 5b8d53b7f763250001cb5eb6 createdAt Mon Sep 03 2018 15:31:03 GMT+0000 (UTC)
web_1            | 2018-09-03 15:31:03 LOG [DSModel._readFromMapping] Reading mapping :  { _id: 5b8d53b7f763250001cb5eb8,
web_1            |   opInfo: { generated: 'Athena' },
web_1            |   fileDataRef: 5b8d53b7f763250001cb5eb6,
web_1            |   entityRef: 5b8d53b7f763250001cb5eb4,
web_1            |   isDeleted: false,
web_1            |   createdAt: 2018-09-03T15:31:03.872Z }
web_1            | 2018-09-03 15:31:03 LOG [DSModel.readData] got 2 bytes of data
web_1            | 2018-09-03 15:31:03 ERROR [getAllNetworks] Error in fetching.  Error: nodes not found
web_1            |     at /usr/src/mappr/server/datasys/datasys_model.js:761:35
web_1            | From previous event:
web_1            |     at /usr/src/mappr/server/datasys/datasys_model.js:759:22
web_1            |     at runCallback (timers.js:810:20)
web_1            |     at tryOnImmediate (timers.js:768:5)
web_1            |     at processImmediate [as _immediateCallback] (timers.js:745:5)
web_1            | From previous event:
web_1            |     at readNetworkFromRecord (/usr/src/mappr/server/datasys/datasys_model.js:750:10)
web_1            |     at Object.readNetwork (/usr/src/mappr/server/datasys/datasys_model.js:784:12)
web_1            |     at /usr/src/mappr/server/datasys/datasys_controller.js:160:28
web_1            |     at arrayMap (/usr/src/mappr/node_modules/lodash/index.js:1406:25)
web_1            |     at Function.map (/usr/src/mappr/node_modules/lodash/index.js:6710:14)
web_1            |     at getAllNetworks (/usr/src/mappr/server/datasys/datasys_controller.js:159:39)
web_1            |     at Layer.handle [as handle_request] (/usr/src/mappr/node_modules/express/lib/router/layer.js:95:5)
web_1            |     at next (/usr/src/mappr/node_modules/express/lib/router/route.js:137:13)
web_1            |     at Route.dispatch (/usr/src/mappr/node_modules/express/lib/router/route.js:112:3)
web_1            |     at Layer.handle [as handle_request] (/usr/src/mappr/node_modules/express/lib/router/layer.js:95:5)
web_1            |     at /usr/src/mappr/node_modules/express/lib/router/index.js:281:22
web_1            |     at Function.process_params (/usr/src/mappr/node_modules/express/lib/router/index.js:335:12)
web_1            |     at next (/usr/src/mappr/node_modules/express/lib/router/index.js:275:10)
web_1            |     at Function.handle (/usr/src/mappr/node_modules/express/lib/router/index.js:174:3)
web_1            |     at router (/usr/src/mappr/node_modules/express/lib/router/index.js:47:12)
web_1            |     at Layer.handle [as handle_request] (/usr/src/mappr/node_modules/express/lib/router/layer.js:95:5)
web_1            |     at trim_prefix (/usr/src/mappr/node_modules/express/lib/router/index.js:317:13)
web_1            |     at /usr/src/mappr/node_modules/express/lib/router/index.js:284:7
web_1            |     at param (/usr/src/mappr/node_modules/express/lib/router/index.js:354:14)
web_1            |     at paramCallback (/usr/src/mappr/node_modules/express/lib/router/index.js:401:21)
web_1            |     at /usr/src/mappr/server/main_router.js:183:17
web_1            |     at /usr/src/mappr/server/project/proj_model.js:40:17
web_1            |     at model.Query.<anonymous> (/usr/src/mappr/node_modules/mongoose/lib/model.js:4081:16)
web_1            |     at /usr/src/mappr/node_modules/kareem/index.js:273:21
web_1            |     at /usr/src/mappr/node_modules/kareem/index.js:131:16
web_1            | GET /api/orgs/5a6f9c2003f1625904ac137f/projects/5b8d53537a7d8a0014b0cf45/networks 500 22.787 ms - -
```

**Comment by ericberlow** [comment]
@mandeepm91  - it was the one you uploaded (that is attached above)- but i think i misunderstood the problem. the project now says it has no nodes even though they were uploaded.  If I upload it and link by 'keywords' it works - though the  color is 'original color' when it should be 'cluster' and the layout should be grouped by cluster.    I uploaded it here to this project http://openmappr.org/projects/5b8d69c0ec57ea001735b079

**Comment by ericberlow** [comment]
I wouldn't worry too much about the error of linking by abstract - this is something we need to fix in the onboarding - it should be not possible to do what he did - it makes no sense - 'abstract' shouldn't have been presented to him as an option to 'link by'... when someone is new and first loads a project, we need a smarter flow to make sure that people don't make mistakes...

**Comment by ericberlow** [comment]
Thanks @mandeepm91 ! that's interesting about Alchemy - you might want to check with vish on that too. We haven't used the alchemy api in awhile as it requires a subscription. I think also IBM has depricated Alchemy since they acquired it:  https://www.ibm.com/watson/developercloud/alchemy-language.html   Re onboarding flow - yes, it requires some good design thinking to spec out - I am scheduled to meet with Rich next week. I'll keep you posted. thanks!
